language: php

php:
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update
  - composer validate

install:
  - composer install --prefer-source

script:
  - composer ci

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
